# Generated by Django 2.2.2 on 2019-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=200)),
                ('bauthor', models.CharField(max_length=200)),
                ('bquantity', models.CharField(max_length=100)),
            ],
        ),
    ]
